/*
 * This source file was generated by the Gradle 'init' task
 */
package com.webserver.core;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MessageUtilsTest {
    @Test void testGetMessage() {

    }
}
