image: openjdk:21-jdk-slim

stages:
  - build
  - test
  - package

cache:
  paths:
    - .gradle/
    - build/

build:
  stage: build
  script:
    - ./gradlew build -x test

test:
  stage: test
  script:
    - ./gradlew test

package:
  stage: package
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/

variables:
  API_TOKEN: $DEPLOYMENT_TOKEN
  APP_PATH: '$CI_PROJECT_DIR/cloudle_ui'

deploy:
  stage: deploy
  image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy
  script:
    - echo "App deployed successfully."
