stages:
  - build
  - deploy

variables:
  APP_PATH: '$CI_PROJECT_DIR/cloudle_ui'               # Your frontend source folder
  OUTPUT_LOCATION: '$CI_PROJECT_DIR/cloudle_ui/build'  # Where the build output will be
  API_LOCATION: ''                                     # Leave blank if no Azure Functions
  AZURE_STATIC_WEB_APPS_API_TOKEN: $AZURE_STATIC_WEB_APPS_API_TOKEN

# Build the frontend
build:
  stage: build
  image: node:18
  script:
    - cd $APP_PATH
    - npm ci
    - npm run build
  artifacts:
    paths:
      - $OUTPUT_LOCATION

# Deploy to Azure
deploy:
  stage: deploy
  image: node:18
  script:
    - npm install -g @azure/static-web-apps-cli
    - echo "Verifying build folder:"
    - ls -la $OUTPUT_LOCATION
    - swa deploy \
        --app-location "$APP_PATH" \
        --output-location "$OUTPUT_LOCATION" \
        --api-location "$API_LOCATION" \
        --deployment-token "$AZURE_STATIC_WEB_APPS_API_TOKEN" \
        --env production
