
stages:
  - build
  - deploy

variables:
  APP_LOCATION: 'cloudle_ui'               # folder with source
  OUTPUT_LOCATION: 'cloudle_ui/build'      # folder with build output
  API_LOCATION: 'api'                      # or "" if no API

build:
  stage: build
  image: node:18
  script:
    - cd $APP_LOCATION
    - npm ci
    - npm run build
  artifacts:
    paths:
      - $OUTPUT_LOCATION

deploy:
  stage: deploy
  image: node:18
  script:
    - npm install -g @azure/static-web-apps-cli
    - echo "Verifying build folder:"
    - ls -la $OUTPUT_LOCATION
    - swa deploy \
        --app-location "$APP_LOCATION" \
        --output-location "$OUTPUT_LOCATION" \
        --api-location "$API_LOCATION" \
        --deployment-token "$AZURE_STATIC_WEB_APPS_API_TOKEN" \
        --env production
