/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Azure stk bom
    implementation(platform("com.azure:azure-sdk-bom:1.2.32"))

    implementation("com.azure:azure-storage-blob")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.webserver.core.Server"
//    mainClass = "com.webserver.azure.AzureBlobInterface"
}
