/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application

    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {

    testImplementation("org.junit.jupiter:junit-jupiter:5.9.3")

    implementation("org.slf4j:slf4j-simple:2.0.9")

    implementation("com.microsoft.sqlserver:mssql-jdbc:10.2.0.jre17")

    // Azure stk bom
    implementation(platform("com.azure:azure-sdk-bom:1.2.32"))
    implementation("com.microsoft.azure:applicationinsights-core:2.6.4")
    implementation("com.azure:azure-core:1.40.0")
    implementation("com.azure:azure-storage-blob")
    implementation("com.google.code.gson:gson:2.10")
    implementation ("io.github.cdimascio:dotenv-java:3.0.0")

}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.webserver.core.Server"
}

tasks.jar {
    manifest {
        attributes["Main-Class"] = application.mainClass.get()
    }

    from("webroot") {
        into("webroot")
    }
}

tasks.shadowJar {
    manifest {
        attributes["Main-Class"] = application.mainClass.get()
    }

    from("../webroot") {
        into("webroot")
    }

    archiveBaseName.set("cloudle")
    archiveClassifier.set("")
    archiveVersion.set("")
    mergeServiceFiles()

}
